inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb" # スキーマファイルは自動生成されるため除外
    - "bin/*" # ビンスクリプトは除外
    - "node_modules/**/*" # フロントエンド依存関係は除外
    - "vendor/**/*" # サードパーティのソースコードは除外
    - "config/initializers/sorcery.rb"

# 国際化の無効化
Rails/I18nLocaleTexts:
  Enabled: false

# Rails固有のコーディングスタイルを適用
Rails:
  Enabled: true

# メトリクス（長さや複雑さに関するルール）の調整
Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb" # 環境設定ファイルは除外
    - "config/routes.rb" # ルーティングファイルは除外
    - "spec/**/*.rb" # RSpecのファイルは除外
Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"
  Max: 25
Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"
  Max: 28

# ドキュメンテーションコメントの強制を無効化
Style/Documentation:
  Enabled: false

# 文字列リテラルの引用符のスタイル（デフォルトはシングルクォートを推奨）
Style/StringLiterals:
  EnforcedStyle: single_quotes

# その他のカスタム設定...
Layout/LineLength:
  Max: 120 # 行の最大長を120に設定

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - after
    - ログイン後
    - 認証情報が正しい場合
    - PWに誤りがある場合
    - 入力情報正常系
    - 入力情報異常系

RSpec/NestedGroups:
  Enabled: true
  Max: 4 # ネストレベルを4に増加

RSpec/ExampleLength:
  Enabled: true
  Max: 8 # 例の最大行数を8に増加

Capybara/ClickLinkOrButtonStyle:
  Enabled: false # Capybaraのクリックスタイルの強制を無効化

RSpec/MultipleExpectations:
  Max: 5 # 一つのitブロック内で許可するexpectationの最大数を5に設定

# Security/Openのチェックを無視
Security/Open:
  Exclude:
    - "app/controllers/oauths_controller.rb"
