services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data_issue:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - node_modules_issue:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      GOOGLE_CLIENT_ID: dummy_client_id
      GOOGLE_CLIENT_SECRET: dummy_client_secret
      SENDER_ADDRESS: dummy@example.com
    ports:
      - "3006:3000"
    depends_on:
      - db

volumes:
  postgres_data_issue:
  node_modules_issue:
