services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SENDER_ADDRESS: ${SENDER_ADDRESS}
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules:
